Add all files

diff --git a/package/kernel/mac80211/patches/build/001-fix_build.patch b/package/kernel/mac80211/patches/build/001-fix_build.patch
--- a/package/kernel/mac80211/patches/build/001-fix_build.patch
+++ b/package/kernel/mac80211/patches/build/001-fix_build.patch
@@ -27,7 +27,11 @@
  	@set -e ; test -f local-symbols || (						\
  	echo "/--------------"								;\
  	echo "| You shouldn't run make in the backports tree, but only in"		;\
+<<<<<<< HEAD
 @@ -60,57 +62,62 @@ mrproper:
+=======
+@@ -60,58 +62,62 @@ mrproper:
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
  	echo "| (that isn't currently running.)"					;\
  	echo "\\--"									;\
  	false)
@@ -56,12 +60,22 @@
 -			done								\
 -		) > Kconfig.kernel							;\
 -		kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) M=$(BACKPORT_DIR)	\
+<<<<<<< HEAD
 -			kernelversion |	sed 's/^\(\([3-6]\|2\.6\)\.[0-9]\+\).*/\1/;t;d');\
 -		test "$$kver" != "" || echo "Kernel version parse failed!"		;\
 -		test "$$kver" != ""							;\
 -		kvers="$$kvers $$(seq 0 20 | sed 's/^/4./')"				;\
 -		kvers="$$kvers $$(seq 0 19 | sed 's/^/5./')"				;\
 -		kvers="$$kvers $$(seq 0 20 | sed 's/^/6./')"				;\
+=======
+-			kernelversion |	sed 's/^\(\([3-5]\|2\.6\)\.[0-9]\+\).*/\1/;t;d');\
+-		test "$$kver" != "" || echo "Kernel version parse failed!"		;\
+-		test "$$kver" != ""							;\
+-		kvers="$$(seq 14 39 | sed 's/^/2.6./')"					;\
+-		kvers="$$kvers $$(seq 0 19 | sed 's/^/3./')"				;\
+-		kvers="$$kvers $$(seq 0 20 | sed 's/^/4./')"				;\
+-		kvers="$$kvers $$(seq 0 99 | sed 's/^/5./')"				;\
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 -		print=0									;\
 -		for v in $$kvers ; do							\
 -			if [ "$$print" = "1" ] ; then					\
@@ -111,6 +125,7 @@
 +	@echo " done."
 +
 +Kconfig.versions: Kconfig.kernel
+<<<<<<< HEAD
 +	@kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) M=$(BACKPORT_DIR)	\
 +		kernelversion |	sed 's/^\(\([3-6]\|2\.6\)\.[0-9]\+\).*/\1/;t;d');\
 +	test "$$kver" != "" || echo "Kernel version parse failed!"		;\
@@ -118,6 +133,16 @@
 +	kvers="$$kvers $$(seq 0 20 | sed 's/^/4./')"				;\
 +	kvers="$$kvers $$(seq 0 19 | sed 's/^/5./')"				;\
 +	kvers="$$kvers $$(seq 0 20 | sed 's/^/6./')"				;\
+=======
++	@kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) M=$(BACKPORT_DIR) \
++		kernelversion |	sed 's/^\(\([3-5]\|2\.6\)\.[0-9]\+\).*/\1/;t;d');\
++	test "$$kver" != "" || echo "Kernel version parse failed!"		;\
++	test "$$kver" != ""							;\
++	kvers="$$(seq 14 39 | sed 's/^/2.6./')"					;\
++	kvers="$$kvers $$(seq 0 19 | sed 's/^/3./')"				;\
++	kvers="$$kvers $$(seq 0 20 | sed 's/^/4./')"				;\
++	kvers="$$kvers $$(seq 0 99 | sed 's/^/5./')"				;\
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 +	print=0									;\
 +	for v in $$kvers ; do							\
 +		if [ "$$print" = "1" ] ; then					\
@@ -125,9 +150,14 @@
 +			echo "    def_bool y"					;\
 +		fi								;\
 +		if [ "$$v" = "$$kver" ] ; then print=1 ; fi			;\
+<<<<<<< HEAD
 +	done > Kconfig.versions							;\
 +	# RHEL as well, sadly we need to grep for it				;\
 +	RHEL_MAJOR=$$(grep '^RHEL_MAJOR' $(KERNEL_MAKEFILE) | 			\
+=======
++	done > $@
++	@RHEL_MAJOR=$$(grep '^RHEL_MAJOR' $(KERNEL_MAKEFILE) | 			\
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 +				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')		;\
 +	RHEL_MINOR=$$(grep '^RHEL_MINOR' $(KERNEL_MAKEFILE) | 			\
 +				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')		;\
diff --git a/package/network/services/dropbear/files/dropbear.init b/package/network/services/dropbear/files/dropbear.init
--- a/package/network/services/dropbear/files/dropbear.init
+++ b/package/network/services/dropbear/files/dropbear.init
@@ -8,6 +8,7 @@ STOP=50
 USE_PROCD=1
 PROG=/usr/sbin/dropbear
 NAME=dropbear
+<<<<<<< HEAD
 
 extra_command "killclients" "Kill ${NAME} processes except servers and yourself"
 
@@ -49,14 +50,41 @@ file_verify()
 
 # $1 - file_verify() return code
 file_errmsg()
+=======
+PIDCOUNT=0
+
+extra_command "killclients" "Kill ${NAME} processes except servers and yourself"
+
+_dropbearkey()
+{
+	/usr/bin/dropbearkey "$@" 0<&- 1>&- 2>&-
+}
+
+# $1 - host key file name
+hk_verify()
+{
+	[ -f "$1" ] || return 1
+	[ -s "$1" ] || return 2
+	_dropbearkey -y -f "$1" || return 3
+	return 0
+}
+
+# $1 - hk_verify() return code
+hk_errmsg()
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 {
 	case "$1" in
 	0) ;;
 	1) echo "file does not exist" ;;
+<<<<<<< HEAD
 	2) echo "file has wrong owner (must be owned by root)" ;;
 	3) echo "file has wrong permissions (must not have group/other write bit)" ;;
 	4) echo "file has zero length" ;;
 	5) echo "file is not valid host key or not supported" ;;
+=======
+	2) echo "file has zero length" ;;
+	3) echo "file is not valid host key or not supported" ;;
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 	*) echo "unknown error" ;;
 	esac
 }
@@ -66,6 +94,7 @@ file_errmsg()
 hk_config()
 {
 	local x m
+<<<<<<< HEAD
 	file_verify "$2" ; x=$?
 	if [ "$x" = 0 ] ; then
 		procd_append_param command -r "$2"
@@ -159,15 +188,91 @@ warn_multiple_interfaces()
 	  "Consider creating per-interface instances instead!"
 }
 
+=======
+	hk_verify "$2"; x=$?
+	case "$x" in
+	0)	procd_append_param command -r "$2"
+		;;
+	*)	m=$(hk_errmsg "$x")
+		logger -t "${NAME}" -p daemon.warn \
+		  "option '$1', value '$2': $m, skipping"
+		;;
+	esac
+}
+
+# $1 - host key file name
+hk_config__keyfile()
+{
+	hk_config 'keyfile' "$1"
+}
+
+hk_generate_as_needed()
+{
+	local kdir kgen ktype tdir kcount tfile
+	kdir='/etc/dropbear'
+
+	kgen=''
+	for ktype in ed25519 ecdsa rsa; do
+		hk_verify "${kdir}/dropbear_${ktype}_host_key" && continue
+
+		kgen="${kgen} ${ktype}"
+	done
+
+	[ -z "${kgen}" ] && return
+
+	tdir=$(mktemp -d); chmod 0700 "${tdir}"
+
+	kcount=0
+	for ktype in ${kgen}; do
+		tfile="${tdir}/dropbear_${ktype}_host_key"
+
+		if ! _dropbearkey -t ${ktype} -f "${tfile}"; then
+			# unsupported key type
+			rm -f "${tfile}"
+			continue
+		fi
+
+		kcount=$((kcount+1))
+	done
+
+	if [ ${kcount} -ne 0 ]; then
+		mkdir -p "${kdir}"; chmod 0700 "${kdir}"; chown root "${kdir}"
+		mv -f "${tdir}/"* "${kdir}/"
+	fi
+
+	rm -rf "${tdir}"
+}
+
+append_ports()
+{
+	local ipaddrs="$1"
+	local port="$2"
+
+	[ -z "$ipaddrs" ] && {
+		procd_append_param command -p "$port"
+		return
+	}
+
+	for addr in $ipaddrs; do
+		procd_append_param command -p "$addr:$port"
+	done
+}
+
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 validate_section_dropbear()
 {
 	uci_load_validate dropbear dropbear "$1" "$2" \
 		'PasswordAuth:bool:1' \
 		'enable:bool:1' \
+<<<<<<< HEAD
 		'DirectInterface:string' \
 		'Interface:string' \
 		'GatewayPorts:bool:0' \
 		'ForceCommand:string' \
+=======
+		'Interface:string' \
+		'GatewayPorts:bool:0' \
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 		'RootPasswordAuth:bool:1' \
 		'RootLogin:bool:1' \
 		'rsakeyfile:file' \
@@ -177,17 +282,27 @@ validate_section_dropbear()
 		'SSHKeepAlive:uinteger:300' \
 		'IdleTimeout:uinteger:0' \
 		'MaxAuthTries:uinteger:3' \
+<<<<<<< HEAD
 		'RecvWindowSize:uinteger:262144' \
+=======
+		'RecvWindowSize:uinteger:0' \
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 		'mdns:bool:1'
 }
 
 dropbear_instance()
 {
+<<<<<<< HEAD
+=======
+	local ipaddrs
+
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 	[ "$2" = 0 ] || {
 		echo "validation failed"
 		return 1
 	}
 
+<<<<<<< HEAD
 	[ "${enable}" = "1" ] || return 1
 
 	local iface ndev ipaddrs
@@ -351,6 +466,41 @@ dropbear_instance()
 		fi
 		procd_append_param command -W "${RecvWindowSize}"
 	}
+=======
+	[ -n "${Interface}" ] && {
+		[ -n "${BOOT}" ] && return 0
+
+		network_get_ipaddrs_all ipaddrs "${Interface}" || {
+			echo "interface ${Interface} has no physdev or physdev has no suitable ip"
+			return 1
+		}
+	}
+
+	[ "${enable}" = "0" ] && return 1
+	PIDCOUNT="$(( ${PIDCOUNT} + 1))"
+	local pid_file="/var/run/${NAME}.${PIDCOUNT}.pid"
+
+	procd_open_instance
+	procd_set_param command "$PROG" -F -P "$pid_file"
+	[ "${PasswordAuth}" -eq 0 ] && procd_append_param command -s
+	[ "${GatewayPorts}" -eq 1 ] && procd_append_param command -a
+	[ "${RootPasswordAuth}" -eq 0 ] && procd_append_param command -g
+	[ "${RootLogin}" -eq 0 ] && procd_append_param command -w
+	if [ -n "${rsakeyfile}" ]; then
+		logger -t ${NAME} -p daemon.warn \
+			"option 'rsakeyfile' is considered to be deprecated and" \
+			"will be removed in future releases, use 'keyfile' instead"
+		hk_config 'rsakeyfile' "${rsakeyfile}"
+	fi
+	config_list_foreach "$1" "keyfile" hk_config__keyfile
+	[ -n "${BannerFile}" ] && procd_append_param command -b "${BannerFile}"
+	append_ports "${ipaddrs}" "${Port}"
+	[ "${IdleTimeout}" -ne 0 ] && procd_append_param command -I "${IdleTimeout}"
+	[ "${SSHKeepAlive}" -ne 0 ] && procd_append_param command -K "${SSHKeepAlive}"
+	[ "${MaxAuthTries}" -ne 0 ] && procd_append_param command -T "${MaxAuthTries}"
+	[ "${RecvWindowSize}" -gt 0 -a "${RecvWindowSize}" -le 1048576 ] && \
+		procd_append_param command -W "${RecvWindowSize}"
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 	[ "${mdns}" -ne 0 ] && procd_add_mdns "ssh" "tcp" "$Port" "daemon=dropbear"
 	procd_set_param respawn
 	procd_close_instance
@@ -358,6 +508,7 @@ dropbear_instance()
 
 load_interfaces()
 {
+<<<<<<< HEAD
 	local enable
 	config_get_bool enable "$1" enable 1
 	[ "${enable}" = "1" ] || return 0
@@ -373,6 +524,12 @@ load_interfaces()
 		iface=$(normalize_list "${iface}")
 	fi
 	interfaces="${interfaces} ${iface}"
+=======
+	config_get interface "$1" Interface
+	config_get enable "$1" enable 1
+
+	[ "${enable}" = "1" ] && interfaces=" ${interface} ${interfaces}"
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 }
 
 boot()
@@ -384,7 +541,10 @@ boot()
 start_service()
 {
 	hk_generate_as_needed
+<<<<<<< HEAD
 	file_verify /etc/dropbear/authorized_keys config
+=======
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 
 	. /lib/functions.sh
 	. /lib/functions/network.sh
@@ -397,6 +557,7 @@ service_triggers()
 {
 	local interfaces
 
+<<<<<<< HEAD
 	procd_add_config_trigger "config.change" "${NAME}" /etc/init.d/dropbear reload
 
 	config_load "${NAME}"
@@ -405,6 +566,15 @@ service_triggers()
 	[ -n "${interfaces}" ] && {
 		local n
 		for n in $(printf '%s\n' ${interfaces} | sort -u) ; do
+=======
+	procd_add_config_trigger "config.change" "dropbear" /etc/init.d/dropbear reload
+
+	config_load "${NAME}"
+	config_foreach load_interfaces dropbear
+
+	[ -n "${interfaces}" ] && {
+		for n in $interfaces ; do
+>>>>>>> 712839d4c6 (Removed unwanted submodules from index)
 			procd_add_interface_trigger "interface.*" $n /etc/init.d/dropbear reload
 		done
 	}
